version: '3.8'

services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=oracle123
    volumes:
      - oracle_data:/opt/oracle/oradata
    container_name: oracle-xe

  page-rendering-app:
    image: webc0llab/page-rendering-unit:latest
    pull_policy: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - oracle-db
    container_name: page-rendering-unit

volumes:
  oracle_data: