version: '3.8'

services:
  page-rendering-app:
    image: webc0llab/page-rendering-unit:latest
    pull_policy: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    container_name: page-renderinstill dg-unit