version: '3.8'

services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=oracle123
    volumes:
      - oracle_data:/opt/oracle/oradata
    container_name: oracle-xe

  page-rendering-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@host.docker.internal:1521:XE
      - SPRING_DATASOURCE_USERNAME=system
      - SPRING_DATASOURCE_PASSWORD=oracle123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - oracle-db
    container_name: page-rendering-unit

volumes:
  oracle_data: