-- Oracle Database Schema for Page Rendering Unit

-- Page Metadata Table
CREATE TABLE page_metadata (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    page_id VARCHAR2(100) NOT NULL UNIQUE,
    title VARCHAR2(200) NOT NULL,
    description CLOB,
    keywords VARCHAR2(500),
    author VARCHAR2(100),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_active NUMBER(1) DEFAULT 1
);

-- Branding Configuration Table
CREATE TABLE branding_config (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_name VARCHAR2(100) NOT NULL UNIQUE,
    logo_url VARCHAR2(500),
    primary_color VARCHAR2(7),
    secondary_color VARCHAR2(7),
    font_family VARCHAR2(100),
    theme_name VARCHAR2(50),
    css_overrides CLOB,
    is_active NUMBER(1) DEFAULT 1,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Performance Metrics Table
CREATE TABLE performance_metrics (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    page_id VARCHAR2(100) NOT NULL,
    load_time_ms NUMBER NOT NULL,
    render_time_ms NUMBER,
    resource_count NUMBER,
    page_size_kb NUMBER,
    user_agent VARCHAR2(500),
    device_type VARCHAR2(50),
    recorded_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Responsive Breakpoints Configuration
CREATE TABLE responsive_breakpoints (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_type VARCHAR2(50) NOT NULL UNIQUE,
    min_width NUMBER NOT NULL,
    max_width NUMBER,
    grid_columns NUMBER DEFAULT 12,
    is_active NUMBER(1) DEFAULT 1
);

-- Create indexes
CREATE INDEX idx_page_id ON performance_metrics(page_id);
CREATE INDEX idx_recorded_date ON performance_metrics(recorded_date);