name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      oracle:
        image: gvenzl/oracle-xe:21-slim
        env:
          ORACLE_PASSWORD: oracle123
        ports:
          - 1521:1521
        options: --health-cmd="sqlplus -s system/oracle123@XE <<<'SELECT 1 FROM dual;'" --health-interval=30s --health-timeout=10s --health-retries=5
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Wait for Oracle
      run: |
        timeout 300 bash -c 'until docker exec $(docker ps -q --filter ancestor=gvenzl/oracle-xe:21-slim) sqlplus -s system/oracle123@XE <<<"SELECT 1 FROM dual;"; do sleep 5; done'
    - name: Setup Oracle Schema
      run: |
        docker exec $(docker ps -q --filter ancestor=gvenzl/oracle-xe:21-slim) sqlplus -s system/oracle123@XE <<EOF
        CREATE TABLE page_metadata (id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, page_id VARCHAR2(100) NOT NULL UNIQUE, title VARCHAR2(200) NOT NULL, description CLOB, keywords VARCHAR2(500), author VARCHAR2(100), created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, is_active NUMBER(1) DEFAULT 1);
        CREATE TABLE branding_config (id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, config_name VARCHAR2(100) NOT NULL UNIQUE, logo_url VARCHAR2(500), primary_color VARCHAR2(7), secondary_color VARCHAR2(7), font_family VARCHAR2(100), theme_name VARCHAR2(50), css_overrides CLOB, is_active NUMBER(1) DEFAULT 1, created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
        CREATE TABLE performance_metrics (id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, page_id VARCHAR2(100) NOT NULL, load_time_ms NUMBER NOT NULL, render_time_ms NUMBER, resource_count NUMBER, page_size_kb NUMBER, user_agent VARCHAR2(500), device_type VARCHAR2(50), recorded_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
        CREATE TABLE responsive_breakpoints (id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, device_type VARCHAR2(50) NOT NULL UNIQUE, min_width NUMBER NOT NULL, max_width NUMBER, grid_columns NUMBER DEFAULT 12, is_active NUMBER(1) DEFAULT 1);
        INSERT INTO page_metadata (page_id, title, description, keywords, author, is_active) VALUES ('landing-home', 'DATABASE CONNECTION TEST', 'Test data from Oracle', 'test, oracle', 'Test Team', 1);
        COMMIT;
        EOF
    - name: Run tests
      run: mvn clean test -Dspring.profiles.active=test
      env:
        SPRING_DATASOURCE_URL: jdbc:oracle:thin:@localhost:1521:XE

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Build JAR
      run: mvn clean package -DskipTests
    
    - name: Build Docker image
      run: docker build -t page-rendering-unit:${{ github.sha }} .
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Push to Docker Hub
      run: |
        docker tag page-rendering-unit:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/page-rendering-unit:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/page-rendering-unit:latest